Repository eveseat/web, pull requests merged in 2019-02, with the labels that each got.

#275 Fix corp killmails table header missarrangement
  src/resources/views/corporation/killmails.blade.php
Labels: fix

#276 Fix issue 512 related to corp tracking
  src/Http/Controllers/Corporation/TrackingController.php
  src/lang/en/seat.php
  src/resources/views/configuration/users/list.blade.php
  src/resources/views/configuration/users/partials/refresh-token.blade.php
  src/resources/views/corporation/partials/refresh-token.blade.php
  src/resources/views/corporation/tracking.blade.php
Labels: fix

#277 Used wrong attribute for filterColumn
  src/Http/Controllers/Character/ContactsController.php
  src/Http/Controllers/Support/SearchController.php
Labels: fix

#279 Fix character contracts
  src/Http/Controllers/Character/ContractsController.php
Labels: fix

#280 feat(universe): Bump universe resolver to v3 which include factions
  src/Http/Controllers/Support/ResolveController.php
  src/resources/views/character/standings.blade.php
Labels: ESI

#273 Add warning about outdated information.
  src/Http/Composers/CharacterLayout.php
  src/lang/en/seat.php
Labels: enhancement

#274 Add loading spinner to changelog
  src/resources/views/configuration/settings/view.blade.php
Labels: enhancement
