Repository eveseat/web, pull requests merged in 2019-01, with the labels that each got.

#246 Queue balancing
  src/Http/Controllers/Configuration/SeatController.php
  src/Http/Validation/SeatSettings.php
  src/WebServiceProvider.php
  src/lang/cn/seat.php
  src/lang/en/seat.php
  src/lang/ru/seat.php
  src/resources/views/configuration/settings/view.blade.php
  src/resources/views/configuration/workers/global.blade.php
Labels: perf

#250 Corporation tracking
  src/Http/Controllers/Corporation/TrackingController.php
  src/Http/Routes/Corporation/View.php
  src/resources/views/corporation/partials/location.blade.php
  src/resources/views/corporation/partials/refresh-token.blade.php
  src/resources/views/corporation/tracking.blade.php
Labels: enhancement

#269 fix contract filter method. Used previously the wrong attribute.
  src/Http/Controllers/Character/ContractsController.php
Labels: fix

#266 Some refactoring in the service and view to be consistent with character view
  src/Http/Controllers/Corporation/KillmailsController.php
  src/resources/views/corporation/killmails.blade.php
Labels: refactor

#267 Refactor corporation journal to work as in game.
  src/Http/Controllers/Corporation/WalletController.php
  src/resources/views/corporation/wallet/journal/journal.blade.php
Labels: enhancement

#268 Refactor Corporation Market
  src/Http/Controllers/Corporation/MarketController.php
  src/resources/views/corporation/market.blade.php
Labels: enhancement

#256 Name title view
  src/Http/Composers/CharacterLayout.php
  src/Http/Composers/CorporationLayout.php
  src/WebServiceProvider.php
  src/resources/views/character/assets.blade.php
  src/resources/views/character/bookmarks.blade.php
  src/resources/views/character/calendar.blade.php
  src/resources/views/character/contacts.blade.php
  src/resources/views/character/contracts.blade.php
  src/resources/views/character/fittings.blade.php
  src/resources/views/character/industry.blade.php
  src/resources/views/character/intel/journaldetail.blade.php
  src/resources/views/character/intel/notes.blade.php
  src/resources/views/character/intel/standingscompare.blade.php
  src/resources/views/character/intel/summary.blade.php
  src/resources/views/character/killmails.blade.php
  src/resources/views/character/layouts/view.blade.php
  src/resources/views/character/mail.blade.php
  src/resources/views/character/market.blade.php
  src/resources/views/character/mining-ledger.blade.php
  src/resources/views/character/notifications.blade.php
  src/resources/views/character/pi.blade.php
  src/resources/views/character/research.blade.php
  src/resources/views/character/sheet.blade.php
  src/resources/views/character/skills.blade.php
  src/resources/views/character/standings.blade.php
  src/resources/views/character/wallet/journal/journal.blade.php
  src/resources/views/character/wallet/transactions/transactions.blade.php
  src/resources/views/corporation/assets.blade.php
  src/resources/views/corporation/bookmarks.blade.php
  src/resources/views/corporation/contacts.blade.php
  src/resources/views/corporation/contracts.blade.php
  src/resources/views/corporation/industry.blade.php
  src/resources/views/corporation/killmails.blade.php
  src/resources/views/corporation/layouts/view.blade.php
  src/resources/views/corporation/ledger/bountyprizesbymonth.blade.php
  src/resources/views/corporation/ledger/planetaryinteraction.blade.php
  src/resources/views/corporation/ledger/walletsummary.blade.php
  src/resources/views/corporation/market.blade.php
  src/resources/views/corporation/mining/ledger.blade.php
  src/resources/views/corporation/pocos.blade.php
  src/resources/views/corporation/security/log.blade.php
  src/resources/views/corporation/security/roles.blade.php
  src/resources/views/corporation/security/titles.blade.php
  src/resources/views/corporation/standings.blade.php
  src/resources/views/corporation/starbases.blade.php
  src/resources/views/corporation/structures.blade.php
  src/resources/views/corporation/summary.blade.php
  src/resources/views/corporation/tracking.blade.php
  src/resources/views/corporation/wallet/journal/journal.blade.php
  src/resources/views/corporation/wallet/transactions/transactions.blade.php
Labels: enhancement

#259 feat(header): Add a caret near profile user drop-down
  src/resources/assets/css/seat.css
  src/resources/assets/js/seat.js
  src/resources/views/includes/header.blade.php
Labels: enhancement

#245 471 character intel
  src/Http/Controllers/Character/IntelController.php
  src/Http/Routes/Character/View.php
  src/resources/views/character/intel/partials/journalcontentbutton.blade.php
  src/resources/views/character/intel/partials/mailcontentbutton.blade.php
  src/resources/views/character/intel/partials/transactioncontentbutton.blade.php
  src/resources/views/character/intel/summary.blade.php
  src/resources/views/character/partials/topmailread.blade.php
Labels: enhancement

#262 feat(extractions): Design an UI to retrieve pending and active moon-mining extractions
  src/Config/package.corporation.menu.php
  src/Config/web.permissions.php
  src/Http/Controllers/Corporation/ExtractionController.php
  src/Http/Routes/Corporation/View.php
  src/Http/Validation/ProbeReport.php
  src/lang/en/seat.php
  src/resources/views/corporation/extraction/extraction.blade.php
  src/resources/views/corporation/extraction/partials/card-body.blade.php
  src/resources/views/corporation/extraction/partials/card.blade.php
  src/resources/views/corporation/extraction/partials/modal.blade.php
Labels: enhancement

#271 Add ability to filter users for valid or invalid refresh_tokens.
  src/Http/Controllers/Configuration/UserController.php
  src/resources/views/configuration/users/list.blade.php
Labels: enhancement

#270 Issue 453 searchblade improvements
  src/Http/Controllers/Support/SearchController.php
  src/resources/views/search/components/character.blade.php
  src/resources/views/search/components/characterassets.blade.php
  src/resources/views/search/components/corporation.blade.php
  src/resources/views/search/components/mail.blade.php
  src/resources/views/search/components/skills.blade.php
  src/resources/views/search/partials/alliancename.blade.php
  src/resources/views/search/partials/ceoname.blade.php
  src/resources/views/search/partials/charactername.blade.php
  src/resources/views/search/partials/corporationname.blade.php
  src/resources/views/search/partials/mailrecipient.blade.php
Labels: enhancement

#272 fix(contracts): Remove non-existing variable from contract index
  src/Http/Controllers/Corporation/ContractsController.php
Labels: fix
