Repository eveseat/web, pull requests merged in 2020-05, with the labels that each got.

#425 UI enhancement: add progress bar to industry jobs
  src/Http/DataTables/Common/Industrial/AbstractIndustryDataTable.php
  src/resources/views/character/industry.blade.php
  src/resources/views/common/industries/partials/progress.blade.php
  src/resources/views/corporation/industry.blade.php
Labels: enhancement

#421 refactor(auth): ensure user can authenticate if there are no SSO issue
  src/Http/Controllers/Auth/SsoController.php
Labels: fix

#423 Auto Join squad if there are no moderators
  src/Http/Controllers/Squads/ApplicationsController.php
Labels: fix

#428 revert: rollback abstract provider change
  src/WebServiceProvider.php
Labels: fix

#432 feat(sde): explode map into specific entities
  src/Http/Controllers/Character/ContractsController.php
  src/Http/Controllers/Corporation/ContractsController.php
  src/Http/Controllers/Corporation/StructureController.php
  src/Http/Controllers/Corporation/TrackingController.php
  src/Http/Controllers/Support/FastLookupController.php
  src/Http/Controllers/Tools/MoonsController.php
  src/Http/DataTables/Character/Industrial/MiningDataTable.php
  src/Http/DataTables/Common/Industrial/AbstractMiningDataTable.php
  src/Http/DataTables/Common/Military/AbstractKillMailDataTable.php
  src/Http/DataTables/Corporation/Industrial/CustomOfficeDataTable.php
  src/Http/DataTables/Corporation/Industrial/MiningDataTable.php
  src/Http/DataTables/Scopes/Filters/ConstellationScope.php
  src/Http/DataTables/Scopes/Filters/MoonProductScope.php
  src/Http/DataTables/Scopes/Filters/MoonRankScope.php
  src/Http/DataTables/Scopes/Filters/RegionScope.php
  src/Http/DataTables/Scopes/Filters/SystemScope.php
  src/Http/DataTables/Tools/MoonsDataTable.php
  src/Http/Validation/SeatSettings.php
  src/resources/views/character/assets/modals/container/content.blade.php
  src/resources/views/character/partials/miningdetails-button.blade.php
  src/resources/views/common/contracts/modals/details/content.blade.php
  src/resources/views/common/minings/miningsystem.blade.php
  src/resources/views/common/minings/modals/details/content.blade.php
  src/resources/views/corporation/assets/modals/container/content.blade.php
  src/resources/views/corporation/extraction/partials/card-body.blade.php
  src/resources/views/corporation/starbase/status-tab.blade.php
  src/resources/views/corporation/starbase/summary.blade.php
  src/resources/views/corporation/starbases.blade.php
  src/resources/views/corporation/structures/list.blade.php
  src/resources/views/corporation/structures/modals/fitting/content.blade.php
  src/resources/views/partials/location.blade.php
  src/resources/views/partials/planet.blade.php
  src/resources/views/tools/moons/buttons/show.blade.php
  src/resources/views/tools/moons/modals/components/content.blade.php
Labels: enhancement, refactor

#433 fix(sso): prevent invalid button tags to be replaced
  src/Http/Controllers/Auth/LoginController.php
Labels: fix

#427 refactor: move repositories from services package
  src/Http/Composers/Esi.php
  src/Http/Composers/User.php
  src/Http/Controllers/Character/IntelController.php
  src/Http/Controllers/Character/MailController.php
  src/Http/Controllers/Character/PiController.php
  src/Http/Controllers/Character/SkillsController.php
  src/Http/Controllers/Character/WalletController.php
  src/Http/Controllers/Configuration/AccessController.php
  src/Http/Controllers/Configuration/SecurityController.php
  src/Http/Controllers/Configuration/UserController.php
  src/Http/Controllers/Corporation/ExtractionController.php
  src/Http/Controllers/Corporation/LedgerController.php
  src/Http/Controllers/Corporation/MiningLedgerController.php
  src/Http/Controllers/Corporation/SecurityController.php
  src/Http/Controllers/Corporation/StarbaseController.php
  src/Http/Controllers/Corporation/StructureController.php
  src/Http/Controllers/Corporation/SummaryController.php
  src/Http/Controllers/Corporation/TrackingController.php
  src/Http/Controllers/Corporation/WalletController.php
  src/Http/Controllers/HomeController.php
  src/Http/Controllers/Profile/ProfileController.php
  src/Http/Controllers/Support/SearchController.php
  src/Http/Controllers/Tools/StandingsController.php
  src/Http/Validation/StandingsExistingElementAdd.php
  src/Models/User.php
  src/Traits/Stats.php
Labels: refactor

#434 fix: add missing get on extractions
  src/Acl/Policies/CharacterPolicy.php
  src/Acl/Policies/CorporationPolicy.php
  src/Http/Controllers/Corporation/ExtractionController.php
  src/Http/DataTables/Scopes/CharacterMailScope.php
  src/Http/DataTables/Scopes/CharacterScope.php
  src/Http/DataTables/Scopes/CorporationScope.php
  src/Http/DataTables/Scopes/KillMailCharacterScope.php
  src/Http/Validation/ProfileSettings.php
Labels: fix

#435 fix: few fix related to character intel and SSO
  src/Http/Controllers/Character/IntelController.php
  src/Http/Controllers/Configuration/SeatController.php
  src/Http/Controllers/Configuration/SsoController.php
Labels: fix

#436 fix: force rendering for cells containing views
  src/Http/DataTables/Character/CharacterDataTable.php
  src/Http/DataTables/Character/Industrial/ResearchDataTable.php
  src/Http/DataTables/Character/Intel/CalendarDataTable.php
  src/Http/DataTables/Character/Intel/MailDataTable.php
  src/Http/DataTables/Character/Intel/NotificationDataTable.php
  src/Http/DataTables/Common/Financial/AbstractContractDataTable.php
  src/Http/DataTables/Common/Financial/AbstractMarketDataTable.php
  src/Http/DataTables/Common/Financial/AbstractWalletJournalDataTable.php
  src/Http/DataTables/Common/Financial/AbstractWalletTransactionDataTable.php
  src/Http/DataTables/Common/Industrial/AbstractBlueprintDataTable.php
  src/Http/DataTables/Common/Industrial/AbstractIndustryDataTable.php
  src/Http/DataTables/Common/Industrial/AbstractMiningDataTable.php
  src/Http/DataTables/Common/Intel/AbstractAssetDataTable.php
  src/Http/DataTables/Common/Intel/AbstractBookmarkDataTable.php
  src/Http/DataTables/Common/Intel/AbstractContactDataTable.php
  src/Http/DataTables/Common/Intel/AbstractNoteDataTable.php
  src/Http/DataTables/Common/Military/AbstractFittingDataTable.php
  src/Http/DataTables/Common/Military/AbstractKillMailDataTable.php
  src/Http/DataTables/Common/Military/AbstractStandingDataTable.php
  src/Http/DataTables/Configuration/RolesDataTable.php
  src/Http/DataTables/Configuration/UsersDataTable.php
  src/Http/DataTables/Corporation/CorporationDataTable.php
  src/Http/DataTables/Corporation/Industrial/CustomOfficeDataTable.php
  src/Http/DataTables/Corporation/Industrial/MiningDataTable.php
  src/Http/DataTables/Corporation/Intel/LogDataTable.php
  src/Http/DataTables/Squads/CandidatesDataTable.php
  src/Http/DataTables/Squads/MembersDataTable.php
  src/Http/DataTables/Squads/RolesDataTable.php
  src/Http/DataTables/Squads/SquadsDataTable.php
  src/Http/DataTables/Tools/MoonsDataTable.php
  src/resources/views/character/intel/modals/mail.blade.php
  src/resources/views/character/mail.blade.php
  src/resources/views/character/sheet.blade.php
  src/resources/views/common/contracts/modals/details/content.blade.php
Labels: fix

#437 small fix regarding 4.0.x and last merge
  src/Http/Controllers/Corporation/ExtractionController.php
  src/Http/Controllers/Corporation/TrackingController.php
  src/Http/DataTables/Character/Industrial/MiningDataTable.php
  src/Http/DataTables/Common/Financial/AbstractContractDataTable.php
Labels: fix
