Repository eveseat/web, pull requests merged in 2020-03, with the labels that each got.

#388 Squads button view typo fix
  src/resources/views/squads/buttons/application/approve.blade.php
  src/resources/views/squads/buttons/application/reject.blade.php
  src/resources/views/squads/buttons/application/show.blade.php
Labels: fix

#389 Add validation to ensure message set
  src/Http/Controllers/Squads/ApplicationsController.php
Labels: enhancement

#384 fix(configuration): Fix User Management characters display and sort
  src/Http/DataTables/Configuration/UsersDataTable.php
  src/resources/views/configuration/users/partials/character-icon-hover.blade.php
  src/resources/views/configuration/users/partials/character.blade.php
Labels: fix

#393 Permission changes
  src/Config/Permissions/global.php
  src/Config/Permissions/moon.php
  src/Config/package.sidebar.php
  src/Http/DataTables/Tools/MoonsDataTable.php
  src/WebServiceProvider.php
  src/resources/lang/en/permissions.php
  src/resources/views/corporation/extraction/partials/card.blade.php
  src/resources/views/tools/moons/list.blade.php
Labels: enhancement

#396 feat(squads): add guardians front of routes
  src/Http/Controllers/Squads/MembersController.php
  src/Http/Controllers/Squads/SquadsController.php
  src/Http/Middleware/Bouncer/SquadAuthorApplicationBouncer.php
  src/Http/Middleware/Bouncer/SquadMemberBouncer.php
  src/Http/Middleware/Bouncer/SquadModeratorBouncer.php
  src/Http/Routes/Squads/Routes.php
  src/WebServiceProvider.php
  src/resources/views/squads/show.blade.php
Labels: enhancement

#398 feat(squads): improve logging
  src/Http/Controllers/Squads/ApplicationsController.php
  src/Http/Controllers/Squads/MembersController.php
  src/resources/views/squads/buttons/application/action.blade.php
Labels: enhancement

#399 refactor: remove auth mail controller reference
  src/Http/Routes/Auth/Email.php
  src/Http/routes.php
Labels: refactor
