Repository eveseat/web, pull requests merged in 2020-04, with the labels that each got.

#402 style(ci): apply styleCi change requests
  src/Config/Permissions/moon.php
  src/Http/Controllers/Character/IntelController.php
  src/Http/Controllers/Support/ResolveController.php
  src/Http/DataTables/Tools/MoonsDataTable.php
  src/Notifications/EmailVerification.php
  src/database/migrations/2020_03_01_193202_remove_v3_role_permissions.php
  src/database/migrations/2020_03_01_193256_remove_v3_permissions.php
  src/resources/lang/de/wallet.php
Labels: refactor

#394 Feature: generate link that provides another SeAT user access to your characters
  src/Acl/AccessChecker.php
  src/Http/Composers/CharacterLayout.php
  src/Http/Controllers/Profile/ProfileController.php
  src/Http/Routes/Profile/View.php
  src/Models/User.php
  src/Models/UserSharelink.php
  src/database/migrations/2020_03_17_114832_create_user_sharelinks_table.php
  src/resources/lang/en/seat.php
  src/resources/views/profile/view.blade.php
Labels: enhancement

#403 Add name column to corporation structures table
  src/resources/views/corporation/structures/list.blade.php
Labels: enhancement

#408 refactor(search): remove entity name from assets and skills search
  src/resources/views/search/components/character_assets.blade.php
  src/resources/views/search/components/skills.blade.php
Labels: enhancement

#413 fix(acl): update required permission to access moon reporter
  src/Http/Routes/Tools/Moons.php
Labels: fix

#416 Add SDE UI indicator of version match, add SDE to versions report.
  src/resources/views/configuration/settings/view.blade.php
Labels: enhancement
