Repository eveseat/web, pull requests merged in 2021-02, with the labels that each got.

#551 fix: Replace today's date with a string when no remap exists.
  src/resources/lang/en/seat.php
  src/resources/views/character/sheet.blade.php
Labels: enhancement

#552 fix(squads): prevent roles to be completely lost after new squad checks
  src/Models/User.php
  src/Observers/AbstractSquadObserver.php
  src/Observers/SquadMemberObserver.php
Labels: fix

#555 fix(squads): fix reverse member relationship (pivot)
  src/Models/Squads/SquadMember.php
  src/Observers/SquadMemberObserver.php
Labels: fix

#556 tests: update phpunit configuration file
  phpunit.xml
Labels: refactor

#557 fix(squads): update user squads on token recovery
  src/Observers/RefreshTokenObserver.php
Labels: fix

#558 refactor: move web related commands from console package
  src/Commands/Seat/Admin/Login.php
  src/WebServiceProvider.php
  src/database/seeds/ScheduleSeeder.php
Labels: refactor
